apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
spec:
  selector:
    matchLabels:
      app: analytics
  replicas: 3
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
        - name: analytics
          image: boondo/lotto-analytics:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: analytics
spec:
  selector:
    app: analytics
  ports:
    - targetPort: 8000
      port: 8000
  type: NodePort

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: analytics-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: analytics
  minReplicas: 3
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50